### ISSUE TITLE
Update to 0.12.6

### ISSUE THREAD

**Issue by AlexWayfer** [khalilgharbaoui/wkhtmltopdf-binary-edge-alpine#2]
https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6-1

**Comment by khalilgharbaoui** [comment]
@AlexWayfer Feel free to open a PR for this.

**Comment by khalilgharbaoui** [comment]
@AlexWayfer closing this issue now version: 0.12.6.3 of the gem is released

**Comment by AlexWayfer** [comment]
@khalilgharbaoui thank you.
