### ISSUE TITLE
Doesn't work inside GitHub Actions

### ISSUE THREAD

**Issue by AlexWayfer** [khalilgharbaoui/wkhtmltopdf-binary-edge-alpine#3]
```
/.../vendor/bundle/ruby/2.7.0/gems/wkhtmltopdf-binary-edge-alpine-0.12.5.0/libexec/wkhtmltopdf-linux-amd64: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

Probably there should be a note of system dependencies in the README. I had no such problems with [the `wkhtmltopdf-binary` gem](https://github.com/zakird/wkhtmltopdf_binary_gem).

---

After (not simple) installation (via third-party repository) there is another requirement:

```
error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by khalilgharbaoui** [comment]
There has always been a big section in the README:

`Docker dependencies for Alpine Linux`

Which strongly suggests that you need these dependencies if you read between the lines.

Also the binary gem you mentioned does not support alpine. I am closing this issue.
